MainApp/urls.py
from django.urls import path

from . import views

app_name = 'MainApp'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza, name='pizza'),
    path('pizzas/<int:pizza_id>/',views.comment, name='comment'),
    path('comment/<int:pizza_id>/', views.comment, name='comment'),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MainApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainApp/models.py
from django.db import models

from learning_log.settings import MEDIA_URL

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='img',blank=True,null=True)
    

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    Pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE)
    topping_name = models.TextField()
    
    def __str__(self):
        return f"{self.topping_name[:50]}..."

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE)
    comment_entry = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

 
    def __str__(self):
        return f"{self.comment_entry[:50]}..."

MainApp/forms.py
from xml.etree.ElementTree import Comment
from django import forms

from .models import Pizza, Topping, Comment

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['pizza_name']
        labels = {'pizza_name':''}
        

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['topping_name']
        labels = {'topping_name':''}
        widgets = {'topping_name': forms.Textarea(attrs= {'cols':80})}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_entry']
        labels = {'comment_entry':''}
        widgets = {'comment_entry': forms.Textarea(attrs= {'cols':80})}

MainApp/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import  PizzaForm, ToppingForm, CommentForm

# Create your views here.

def index(request):
    return render(request, 'MainApp/index.html')


def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'pizzas':pizzas}

    return render(request, 'MainApp/pizzas.html', context)


def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    topping = pizza.topping_set.all()
    picture = Pizza.picture
    comment = pizza.comment_set.order_by('-date_added')

    context = {'pizza':pizza,'toppings':topping, 'picture': picture, 'comments':comment}

    return render(request, 'MainApp/pizza.html', context)


def comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form=CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.pizza = pizza
            comment.save()
            return redirect('MainApp:pizza',pizza_id=pizza_id)

    context = {'form':form, 'pizza':pizza}

    return render(request, 'MainApp/comment.html', context)

MainApp/templates/mainapp/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>Pizza Planet</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'MainApp:index'%}">
            Pizza Planet</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'MainApp:pizzas'%}">
                        Pizzas</a>
                </li>
            </ul>
        </div>

    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

MainApp/templates/mainapp/comment.html
{% extends "MainApp/base.html" %}


{% block content %}

<p><a href="{% url 'MainApp:pizza' pizza.id %}">{{ pizza }} </a></p>

<p> Add a new comment</p>

<form action="{% url 'MainApp:comment' pizza.id %}" method='post'>

    {% csrf_token %}

    {{form.as_p}}

    <button name="submit">Add comment</button>

</form>

{% endblock content %}

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %}

{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Pizza Planet</h1>

    <p class="lead">Where the Pizza is out of this world!</p>

</div>

<style>
    body {
        background-image: url(https://i.etsystatic.com/9343558/r/il/aaa7cc/1953321814/il_fullxfull.1953321814_he95.jpg)
    }
</style>

{% endblock page_header %}

MainApp/templates/mainapp/pizza.html
{% extends "MainApp/base.html" %}


{% block content %}
<p>
    {{ pizza }}
</p>

<ul>
    {% for e in toppings %}
    <li>
        <p> {{ e.topping_name }}</p>
    </li>
    {% empty %}
    <li> There are no toppings for this pizza.</li>
    {% endfor %}
</ul>

<p>
    <img src="{{ pizza.picture.url }}">
</p>

<p><a href="{% url 'MainApp:comment' pizza.id %}">Add comment</a></p>

<ul>
    {% for c in comments %}
    <li>
        <p> {{ c.comment_entry }}</p>
        <p> {{ c.date_added }}</p>
    </li>
    {% empty %}
    <li> There are no comments for this pizza.</li>
    {% endfor %}
</ul>

{% endblock content %}

MainApp/templates/mainapp/pizzas.html
{% extends "MainApp/base.html" %}

{% block page_header %}
<h1>Pizzas</h1>
{% endblock page_header %}

{% block content %}

<p> Pizzas </p>

<ul>
    {% for t in pizzas %}

    <li>
        <h3>
            <a href="{% url 'MainApp:pizza' t.id %}">{{ t }} </a>
        </h3>
    </li>

    {% empty %}
    <li>
        <h3>No pizzas have been added yet.</h3>
    </li>
    {% endfor %}
</ul>

{% endblock content %}